version: 0.0
os: linux
files:
 - source: target/training.com.training1.war
   destination: /usr/share/apache-tomcat-9.0.39/webapps 

hooks:
 ApplicationStart:
  - location: restart.sh
    timeout: 180
